#ifndef ROBUROC4_CONTROLLERS_HPP
#define ROBUROC4_CONTROLLERS_HPP

#define CONTROL_MODE_OFF		0x00
#define CONTROL_MODE_HELMSMAN 	0x01
#define CONTROL_MODE_TRAJECTORY	0x02

#define LOGGER_MODE_HELMS_START	0x01
#define LOGGER_MODE_HELMS_END	0x02
#define LOGGER_MODE_HELMS_SAVE	0x03
#define LOGGER_MODE_HELMS_PUB	0x04
#define LOGGER_MODE_TRAJ_START	0x05
#define LOGGER_MODE_TRAJ_END	0x06
#define LOGGER_MODE_TRAJ_PUB	0x07

#endif
